# Generated by Django 5.1.5 on 2025-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage', '0002_remove_student_marks_remove_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Chattogram', max_length=100),
        ),
    ]
